substitutions:
  vendor_name: diy
  vendor_friendly: DIY
  device_name: gdo
  device_friendly: GDO

  esphome_name: ${vendor_name}
  esphome_friendly_name: "${vendor_friendly} ${device_friendly}"
  esp8266_board: d1_mini

  cover_open_duration: 1min
  cover_close_duration: 1min

packages:
  common: !include_dir_merge_named packages/common/
  esp8266: !include packages/chip/esp8266.yaml
  api: !include_dir_merge_named packages/api/
  dev: !include_dir_merge_named packages/dev/

esp8266:
  board: ${esp8266_board}

switch:
  - platform: gpio
    pin:
      number: D1
      inverted: true
    id: relay
    restore_mode: "ALWAYS_OFF"
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay

binary_sensor:
  - platform: gpio
    pin:
      number: D5
    id: door_closed

cover:
  - platform: feedback
    name: "${esphome_friendly_name} Cover"
    device_class: garage
    open_action:
      - switch.turn_on: relay
    close_action:
      - switch.turn_on: relay
    stop_action:
      - switch.turn_on: relay
    open_duration: ${cover_open_duration}
    close_duration: ${cover_close_duration}
    close_endstop: door_closed
    has_built_in_endstop: true
