substitutions:
  vendor_name: diy
  vendor_friendly: DIY
  device_name: ota-esp8266
  device_friendly: OTA-ESP8266

  esphome_name: ${vendor_name}
  esphome_friendly_name: "${vendor_friendly} ${device_friendly}"
  esp8266_board: esp01_1m

packages:
  common: !include_dir_merge_named packages/common/
  esp8266: !include packages/chip/esp8266.yaml
  api: !include_dir_merge_named packages/api/
  dev: !include_dir_merge_named packages/dev/

esp8266:
  board: ${esp8266_board}
