substitutions:
  vendor_name: gosund
  vendor_friendly: Gosund
  device_name: wp3
  device_friendly: WP3

  esphome_name: ${vendor_name}
  esphome_friendly_name: "${vendor_friendly} ${device_friendly}"
  switch_relay_restore_mode: "RESTORE_DEFAULT_ON"

packages:
  common: !include_dir_merge_named packages/common/
  esp8266: !include packages/chip/esp8266.yaml
  api: !include_dir_merge_named packages/api/
  dev: !include_dir_merge_named packages/dev/

esp8266:
  board: esp01_1m

status_led:
  pin:
    number: GPIO12
    inverted: True

output:
  - id: led
    platform: gpio
    pin:
      number: GPIO13
      inverted: True

switch:
  - id: relay
    platform: gpio
    name: "${esphome_friendly_name} Relay"
    pin: GPIO14
    restore_mode: ${switch_relay_restore_mode}
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

binary_sensor:
  - id: button
    platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    name: "${esphome_friendly_name} Button"
    on_press:
      - switch.toggle: relay
    internal: True
