substitutions:
  vendor_name: sonoff
  vendor_friendly: Sonoff
  device_name: s31-lite
  device_friendly: S31-Lite

  esphome_name: ${vendor_name}
  esphome_friendly_name: "${vendor_friendly} ${device_friendly}"
  switch_relay_restore_mode: "RESTORE_DEFAULT_ON"

packages:
  common: !include_dir_merge_named ../_common/
  esp8266: !include ../_chip/esp8266.yaml
  api: !include_dir_merge_named ../_api/

esp8266:
  board: esp01_1m

status_led:
  pin:
    number: GPIO13
    inverted: True

switch:
  - platform: gpio
    name: "${esphome_friendly_name} Relay"
    pin: GPIO12
    id: relay
    restore_mode: ${switch_relay_restore_mode}

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${esphome_friendly_name} Button"
    on_press:
      - switch.toggle: relay
    internal: True
    id: button
